author:
- given: Neil D.
  family: Lawrence
  institution: University of Cambridge
  gscholar: r3SJcvoAAAAJ
  twitter: lawrennd
  orcid: 0000-0001-9258-1030
  url: http://inverseprobability.com
layout: lecture
venue: Gaussian Process Summer School
talkcss: https://inverseprobability.com/assets/css/talks.css
postsdir: ../../../mlatcl/gpss/_lectures/
slidesdir: ../../../mlatcl/gpss/slides/
notesdir: ../../../mlatcl/gpss/_notes/
notebooksdir: ../../../mlatcl/gpss/_notebooks/
writediagramsdir: .
scriptsdir: ../scripts/
diagramsdir: ./slides/diagrams/
potx: ../_includes/custom-reference.potx 
dotx: ../_includes/custom-reference.dotx
transition: None
baseurl: "gpss/" # the subpath of your site, e.g. /blog/
url: "https://mlatcl.github.io/" # the base hostname & protocol for your site
ghub:
- organization: lawrennd
  repository: talks
  branch: gh-pages
  directory: _gpss
